

// ignore_for_file: non_constant_identifier_names

class ApiUrl {
  //http://admin.businessgym.in/api/
  //static var baseurl = "http://admin.businessgym.in/api/";
  static var BASEURL="https://saath.lttrbx.in/";
  static var baseurl="https://saath.lttrbx.in/api/";
  static var loginApiUrl = "${baseurl}login_new";
  static var RegisterApiUrl = "${baseurl}register_new";
  static var organizationlist="${baseurl}organization_list";
  static var service_list = "${baseurl}service-list";
  static var provider_list = "${baseurl}provider-list";
  static var add_loan_request = "${baseurl}add-loan-request";
  static var approved_loan_list = "${baseurl}approved-loan-list";
  static var getDocumentCategories = "${baseurl}getDocumentCategories";
  static var getDocumentPendingNumber = "${baseurl}getDocumentPendingNumber";
  static var add_transection = "${baseurl}add-transection";
  static var view_transection = "${baseurl}view-transection";
  static var serviceAdd = "${baseurl}service-add";
  static var viewAdvertisement = "${baseurl}view-advertisement";
  static var viewAdvertismentdetail="${baseurl}view-advertisementdetails";
  static var notificationList = "${baseurl}notification-list";
  static var view_profile = "${baseurl}view-profile";
  static var updateProfile = "${baseurl}update-profile";
  static var removeProfile = "${baseurl}delete-profile-image";
  static var viewNews = "${baseurl}view-news";
  static var getVideos = "${baseurl}getVideos";
  static var getfeedall="${baseurl}get_video_news_quiz_pol?user_id=";
  static var viewVideo = "${baseurl}viewVideo";
  static var getGroups = "${baseurl}getGroups";
  static var getMyGroups = "${baseurl}getMyGroups";
  static var addGroupRequest = "${baseurl}addGroupRequest";
  static var servicedelete = "${baseurl}service-delete";
  static var loantypes = "${baseurl}loan-types";
  static var mfilist = "${baseurl}mfi-list";
  static var getDiscussions = "${baseurl}getDiscussions";
  static var viewoccuaptions = "${baseurl}view-occuaptions";
  static var viewquiz = "${baseurl}view-quiz";
  static var getScoreCount = "${baseurl}find_profile_percentage";
  static var addquiz = "${baseurl}add-quiz";
  static var viewpolls = "${baseurl}view-polls";
  static var addpolls = "${baseurl}add-polls";
  static var getDiscussionComment = "${baseurl}getDiscussionComment";
  static var addDiscussionComment="${baseurl}addDiscussionComment";
  static var providerbookings = "${baseurl}provider_bookings";
  static var quicktransectionreport = "${baseurl}quick-transection-report";
  static var addbusinessWorkURL = "${baseurl}add-work-profile";
  static var workProfileListsURL = "${baseurl}workProfileLists";
  static var deleteWorkProfile = "${baseurl}deleteWorkProfile";
  static var productAdd = "${baseurl}add-product";
  static var productView = "${baseurl}getProducts";
  static var productdelete = "${baseurl}deleteProduct";
  static var videoComment = "${baseurl}get_video_comment_list";
  static var addLikeURL = "${baseurl}add_video_like";
  static var addcommentURL = "${baseurl}add_video_comment";
  static var get_supplier_service = "${baseurl}get_all_supplier_service";
  static var supplier_service_delete = "${baseurl}supplier_service_delete";
  static var get_supplier_product = "${baseurl}get_supplier_product";
  static var delete_supplier_product = "${baseurl}delete_supplier_product";
  static var all_product_list = "${baseurl}all_product_list";
  static var SupplierServiceBySubCategoryID = "${baseurl}SupplierServiceBySubCategoryID";
  static var ProfileView = "${baseurl}getProductAndServiceByProvider";
  static var dynamicNotification = "${baseurl}get_notification?user_id=";
  static var readNotification = "${baseurl}read_notifications";
  static var getprovideproduct="${baseurl}get_provider_product_category";
  static var getservicecategory="${baseurl}get_provider_service_category";
  static var getuser="${baseurl}get/users";
  static var getnearbymeservice="${baseurl}get_nearBy_me_services?type=nearBy";
  static var getnearbymeprocut="${baseurl}get_nearBy_me_products?type=nearBy";
  static var getnearbyratingservice="${baseurl}get_nearBy_me_services?type=byRating";
  static var getnearbyratingproduct="${baseurl}get_nearBy_me_products?type=byRating";
  static var getservicelist="${baseurl}profile_service_list";
  static var getproductlist="${baseurl}profile_product_list";
  static var getsupplierservicelist="${baseurl}service_category";
  static var getsupplierproductlist="${baseurl}product_category";
  static var getservicesubcategorylist="${baseurl}get_sub_category?";
  static var getproductsubcategorylist="${baseurl}product_sub_category?";
  static var getviewprofile="${baseurl}viewProfile";
  static var getleadlist="${baseurl}get_lead";
  static var addlead="${baseurl}add-call-logs";
  static var addmarkasclient="${baseurl}add_mark_as_client";
  static var removeasclient="${baseurl}remove_mark_as_client";
  static var gethomelist="${baseurl}home_page";
  static var getreccomandedservice="${baseurl}get_recomanded_services";
  static var getreccomandedproduct="${baseurl}get_recomanded_products";
  static var getworkprofilelist="${baseurl}workProfileLists";
  static var getservicebyid="${baseurl}get_service_by_user_id?provider_id=";
  static var getproductbyid="${baseurl}get_product_by_user_id?provider_id=";
  static var aboutus="${BASEURL}app-about-us";
  static var ratingreview="${baseurl}rating-user";
  static var addDiscussion = "${baseurl}addDiscussion";
  static var updatelocation="${baseurl}update_location";
  static var provider_document_save = "${baseurl}provider-document-save";
  static var transectionreport = "${baseurl}transection-report";
  static var getSupportSubject = "${baseurl}getSupportSubject";
  static var getproductseller="${baseurl}all-product-list";
  static var getserviceprovider="${baseurl}all-service-list";
  static var getuserreviews = "${baseurl}get-user-reviews";
  static var getworkprofile="${baseurl}workProfileLists";
  static var deleteservice="${baseurl}service-delete";
  static var deleteproduct="${baseurl}deleteProduct";
  static var addviewedprofile="${baseurl}add_viewed";
  static var addleadrating="${baseurl}add_lead_rating";
  static var adduserrating="${baseurl}add_user_rating";
  static var searchFilterUrl = "${baseurl}search";
  static var getuerdetailsbyid="${baseurl}UserDataByID?id=";
  static var addhelpsupport="${baseurl}add-support-request";
  static var addfeedback="${baseurl}addFeedback";
}
